""" init 

Revision ID: 7a4d762a38b5
Revises: 
Create Date: 2025-11-18 02:51:35.645840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a4d762a38b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_department_permissions_code'))
        batch_op.drop_constraint(batch_op.f('uq_department_permissions_dept_code'), type_='unique')
        batch_op.drop_index(batch_op.f('ux_dept_perm_dept_code'))
        batch_op.create_unique_constraint('uq_department_permission', ['department_id', 'permission'])
        batch_op.create_foreign_key(batch_op.f('fk_department_permissions_department_id_departments'), 'departments', ['department_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_department_permissions_department_id_departments'), type_='foreignkey')
        batch_op.drop_constraint('uq_department_permission', type_='unique')
        batch_op.create_index(batch_op.f('ux_dept_perm_dept_code'), ['department_id', 'code'], unique=1)
        batch_op.create_unique_constraint(batch_op.f('uq_department_permissions_dept_code'), ['department_id', 'code'])
        batch_op.create_index(batch_op.f('ix_department_permissions_code'), ['code'], unique=False)

    # ### end Alembic commands ###
